// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vvuTs3NLj8Wxj3kWawJBV7IAjpcQQcY',
    appId: '1:695988236040:android:d87157aca681685a3f06bd',
    messagingSenderId: '695988236040',
    projectId: 'tracklit-f4266',
    storageBucket: 'tracklit-f4266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0M0kX4KogpltviHp_YsWC0uHBf1Qc6N8',
    appId: '1:695988236040:ios:a56b663e2fdd3bb13f06bd',
    messagingSenderId: '695988236040',
    projectId: 'tracklit-f4266',
    storageBucket: 'tracklit-f4266.firebasestorage.app',
    androidClientId: '695988236040-ig74nvcioliutlsajjt01up1kqgi4btb.apps.googleusercontent.com',
    iosClientId: '695988236040-3ctp44nlahe8gksp9gqvirvnc6fhb2qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

}